default:
  push_kubernetes: false
  push_images: true

kubernetes:
  version: v1.23.6

images:
  - registry.k8s.io/ingress-nginx/controller:v1.11
  - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.4
